apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: pr-anomaly-serve
  annotations:
    scenarios.ai.sap.com/description: "Purchase Requisition Anomaly Detection - Serving"
    scenarios.ai.sap.com/name: "pr-anomaly-detection"
    executables.ai.sap.com/description: "Flask serving for PR anomaly predictions"
    executables.ai.sap.com/name: "pr-anomaly-serve"
  labels:
    scenarios.ai.sap.com/id: "pr-anomaly-detection"
    executables.ai.sap.com/id: "pr-anomaly-serve"
    ai.sap.com/version: "1.0.0"
spec:
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: starter
    spec: |
      predictor:
        imagePullSecrets:
        - name: docker-him
        minReplicas: 1
        maxReplicas: 2
        containers:
        - name: kserve-container
          image: docker.io/himanshupensia/pr-anomaly-serve:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
          - name: MODEL_PATH
            value: "/app/models/model.joblib"
          - name: METADATA_PATH
            value: "/app/models/metadata.json"